### ISSUE TITLE
Some builds against Solidus `master` failing due to outdated CI image for Ruby

### ISSUE THREAD

**Issue by forkata** [solidusio/circleci-orbs-extensions#42]
We've started seeing some failures on runs against Solidus `master` due to the fact that we are using a base CI image with Ruby 2.5. We've seen this issue appear when `pry-byebug` and `pry-stack_explorer` are referenced in an extension's `Gemfile`, but it is possible that other gems rely on this as well.

The error in question is
```
NameError: uninitialized constant DidYouMean::PlainFormatter
```

You can see some examples of this error on the Solidus Taxjar and Subscriptions extensions

https://app.circleci.com/pipelines/github/SuperGoodSoft/solidus_taxjar/309/workflows/062db350-ce0e-4916-855b-cc5a7b10fa8a/jobs/326

https://app.circleci.com/pipelines/github/solidusio-contrib/solidus_subscriptions?branch=master&filter=all

If there is interest in moving the base CI image to a more recent and supported version of Ruby, say 2.7, I can open a pull request for that, but first I wanted to see if that is something we would want to do. Let me know if I can provide any more details here.

**Comment by elia** [comment]
@forkata I think this was fixed by https://github.com/solidusio/circleci-orbs-extensions/commit/581046f6

**Comment by forkata** [comment]
Thanks @elia!
